server:
  port: ":8189"

database:
  path: "all2wei.db"

storage:
  type: "minio"  # "local" 或 "minio"

minio:
  endpoint: "minio.6200052.xyz:444"
  access_key_id: "mxrain"
  secret_access_key: "zilidr160"
  use_ssl: true
  bucket_name: "all2wei"
  region: "us-east-1"

jwt:
  secret: "SDD334554321123211"
  expire: 168  # 7 days in hours
